name: testes funcionais de login

on: pull_request

jobs: testes funcionais de login
  continuos-integration: 
    runs-on: ubuntu-latest
    
    steps:
      # Step 2: Configuração do Node.js
        uses: actions/setup-node@v3
        name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: v22.12.0  # ou a versão de Node.js que você usa no projeto

      # Step 3: Instalação das dependências npm
      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test

      # Step 4: Cache para dependências (opcional, mas acelera o build)
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Step 5: Rodar os testes do Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run start  # Caso você precise rodar uma aplicação antes dos testes
          wait-on: 'http://localhost:3000'  # Caso precise esperar o servidor da aplicação rodar
