name: End-to-end tests
on: 
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar
  pull_request:
    branches:
      - main  # Ou a branch que você deseja monitorar para pull requests

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    
    steps:
      # Step 1: Checkout do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Configuração do Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # ou a versão de Node.js que você usa no projeto

      # Step 3: Instalação das dependências npm
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Cache para dependências (opcional, mas acelera o build)
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Step 5: Rodar os testes do Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run start  # Caso você precise rodar uma aplicação antes dos testes
          wait-on: 'http://localhost:3000'  # Caso precise esperar o servidor da aplicação rodar
