name: Pipeline

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        path: automacao-cypress-amazon

    - name: Build with Maven
      run: mvn clean install -f automacao-cypress-amazon/pom.xml