name: testes funcionais de login

on: pull_request

jobs: testes funcionais de login
  continuos-integration: 
    runs-on: ubuntu-latest
    
    steps:
      # Step 2: Configuração do Node.js
        uses: actions/setup-node@v3
        name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: v22.12.0  # ou a versão de Node.js que você usa no projeto

      # Step 3: Instalação das dependências npm
      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test